kind: pipeline
type: kubernetes
name: devops-charts

concurrency:
  limit: 1

steps:
  - name: main build
    image: alpine/helm:3.9.0
    commands:
      - echo https://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
      - apk update
      - apk add yq jq bash
      - helm version
      - helm plugin install https://github.com/chartmuseum/helm-push --version 0
      - helm repo add --username $USERNAME --password $PASSWORD harbordevops https://harbor.devops.indico.io/chartrepo/indico-devops
      - ./upload-charts.sh
    
    environment:
      HELM_EXPERIMENTAL_OCI: 1
      PASSWORD:
        from_secret: harbor_password
      USERNAME:
        from_secret: harbor_username
    when: 
      branch: 
        - main
      event: 
        - push
        - tag


  - name: branch build
    image: alpine/helm:3.9.0
    commands:
      - echo https://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
      - apk update
      - apk add yq jq bash
      - helm version
      - helm plugin install https://github.com/chartmuseum/helm-push --version 0
      - helm repo add --username $USERNAME --password $PASSWORD harbordevops https://harbor.devops.indico.io/chartrepo/indico-devops
      - ./upload-charts.sh "$DRONE_BRANCH-${DRONE_COMMIT_SHA:0:8}"
    
    environment:
      HELM_EXPERIMENTAL_OCI: 1
      PASSWORD:
        from_secret: harbor_password
      USERNAME:
        from_secret: harbor_username
    when:
      event:
        - push
        - tag
      branch:
        exclude:
          - main

image_pull_secrets:
  - harbor_pull_secret

---
kind: secret
name: harbor_pull_secret
get:
  path: tools/drone/devops_harbor_pull_secret
  name: DOCKER_CONFIG_JSON 

---
kind: secret
name: harbor_username
get:
  path: tools/drone/harbor-push-token
  name: username

---
kind: secret
name: harbor_password
get:
  path: tools/drone/harbor-push-token
  name: password
