---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "argo-mutator.fullname" . }}
  namespace: {{ .Release.Namespace }}
 

spec:
  isCA: false
  dnsNames:
    -  {{ include "argo-mutator.fullname" . }}.{{ .Release.Namespace }}.svc
  commonName: {{ include "argo-mutator.fullname" . }}.{{ .Release.Namespace }}.svc
  secretName: {{ include "argo-mutator.fullname" . }}
  duration: 87600h
  renewBefore: 720h
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io