{{- if .Values.validate.create -}}
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.admissionController.certificateName }}
  name: {{ include "argo-mutator.fullname" . }}-validating-webhook
webhooks:
  - name: {{ .Values.validate.serviceName }}.{{ .Release.Namespace }}.svc
    namespaceSelector:
      matchExpressions:
        - {
            key: "kubernetes.io/metadata.name",
            operator: NotIn,
            values: [{{- range .Values.validate.excludeNamespaces }}
              {{ quote . -}},
            {{ end }}
            ]
          }    
        - {
            key: "name",
            operator: NotIn,
            values: [{{- range .Values.mutate.excludeNamespaces }}
              {{ quote . -}},
            {{ end }}
            ]
          }  
        - {
            key: "field.cattle.io/projectId",
            operator: DoesNotExist
          }          

    failurePolicy: Fail
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["applications"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGakNDQWY2Z0F3SUJBZ0lSQUt4RVNNUXY5TjY0VXZvZHRqWjIxZHN3RFFZSktvWklodmNOQVFFTEJRQXcKSXpFaE1COEdBMVVFQXhNWVlYZG9MV0Z5WjI4dGJYVjBZWFJ2Y2k1aGQyZ3VjM1pqTUI0WERUSXpNRGd3T0RFeApNakl6TTFvWERUTXpNRGd3TlRFeE1qSXpNMW93SXpFaE1COEdBMVVFQXhNWVlYZG9MV0Z5WjI4dGJYVjBZWFJ2CmNpNWhkMmd1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMmhOZG16LzYKV3FpWmtwcUs4SUFNN1FadG5UNExWUGYzeUVTYWVxeGZQZnEySk13MHNkWW5ISVk4NlZaOExrMnd4OGJqWDR6NwpZckJEdDU2ZGlFVTNKSjNvT3FRNzY2Z2ZOZUd3Y24rNDBSVWUyR3IwVlkxL1ZEZUFzdk5yZmdReG9zTUMwQTRyCkVFZUQ3R0xTNExYRmFFajFld1NSQUpEaWtTV01kZVlHaisxajZwU2JLOEk3STRHYmFnY2JGMEtEK3h0T3BPcDAKUzRZWmt3T0hzdDk2akdhdE1wbkh6S2FqUGtka0hsQlI0cmRMajgzQmpGZXVZNmNBSnFmanVERGdzSEZjQlc5VwpsMzEwakJROCtnL24yM2FrRFFmZUZhRFpyQjBtcm5hRkVsZW10V3dpU3lHRVluZWZiWjlob0JyNTdidjU5V1kvCnp3amUrWFB6bGZNMUV3SURBUUFCbzBVd1F6QU9CZ05WSFE4QkFmOEVCQU1DQmFBd0RBWURWUjBUQVFIL0JBSXcKQURBakJnTlZIUkVFSERBYWdoaGhkMmd0WVhKbmJ5MXRkWFJoZEc5eUxtRjNhQzV6ZG1Nd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBS2x4YUJlVWNHQW1tTm9HZW5Va1FJak54V043ZmtzWlFxMnpFMjZvVHpuVnJJcU9RNEV3ClpEMzlBYWxYK1NWVk93bC9rLzg0NG41YlVWa0svN25zY3BxdmhPUndVTEh4ZldVN2RGVU5uekpjaW1TUld2dk0KdEJoTkFJS09WT1I3MllROUd5Z2x3OHl6cmEvcjExL2NDaHVib1NQYWRBSzlBNHZFY0llNXlMd0xWK3FjL0JVSwppVUl5cnhBTE5mcTNBekN6cDdwNFRicVZvUDBqYUpGWVE1Q0Z3WG1Cb0dCL3RScWlqZnhORTJ1MWV2N1N0VFBnClRKWEVoUFlqdlFhTVJEaVY3ZnlxbzFYSHFNa3l6cWcyem85cUJVSVJackFBTFlzT2VlSWdRVzc4aU1Kelh5UTQKL3l0M3ZoazEzeUdFRGRZakhPVS9pSUdNWjkySUpYTldzNlE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Values.validate.serviceName }}
        path: /validate
    sideEffects: "None"
    admissionReviewVersions: ["v1"]
{{- end }}
