# Default values for indico-openshift-adm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

admissionController:
  certificateName: adm-argo-mutator

image:
  repository: harbor.devops.indico.io/indico/devops-argo-mutator
  pullPolicy: Always
  tag: latest

imagePullSecrets: 
  - name: harbor-pull-secret

nameOverride: ""
fullnameOverride: ""


clusterRole:
  create: true
  name: "indico-openshift-adm"
  resources:
    [
      "deployments",
      "statefulsets",
      "namespaces",
      "quotas",
      "secrets",
      "rolebindings",
      "configmaps",
      "resourcequotas",
    ]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]


validate:
  create: true
  serviceName: adm-argo-mutator-webhook
  name: "argo-mutator-validate-webhook"
  excludeNamespaces:
    [
      "kube-system",
      "kube-node-lease",
      "kube-public",
    ]

mutate:
  create: true
  serviceName: adm-argo-mutator-mutate
  name: "argo-mutator-mutate-webhook"
  excludeNamespaces:
    [
      "kube-system",
    ]


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "argo-mutator"

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

service:
  create: true
  type: ClusterIP
  port: 443

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
