---
apiVersion: "secrets.hashicorp.com/v1beta1"
kind: "VaultStaticSecret"
metadata:
  name:  vault-thanos-storage
  namespace: default
spec:
  type: "kv-v2"
  namespace: default
  mount: customer-Indico-Devops
  path: thanos-storage
  refreshAfter: 60s
  rolloutRestartTargets:
    - name: p-monitoring-kube-prometheus-prometheus
      kind: StatefulSet
  destination:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    create: true
    name: thanos-storage
  vaultAuthRef: default
