{{- $fullname := include "devops-keycloak-service.fullname" . }}
{{- range .Values.vaultSecrets }}
---
kind: Secret
apiVersion: v1
metadata:
  name:  {{ $fullname }}-{{ .name }}
  annotations:
    avp.kubernetes.io/path: "{{ .path }}"
type: Opaque
stringData:
  {{- range $key, $location := .secrets }}
  {{ $key }}: {{ $location }}
  {{- end }}
{{- end }}