
kube-prometheus-stack:
  enabled: true

  prometheus:
    enabled: false

  grafana:
    enabled: false

grafana:
  enabled: true
 
thanos:
  enabled: true

ingress-nginx:
  enabled: true
  controller:
    replicaCount: 3
  rbac:
    create: true



  