thanos:
  enabled: true
  existingObjstoreSecret: thanos-objstore-config
  persistence:
    size: 1000Gi
    
kube-prometheus-stack:
  enabled: true

  prometheus:
    enabled: false

  grafana:
    enabled: false
