
kube-prometheus-stack:
  enabled: true

  prometheus:
    enabled: false

  grafana:
    enabled: false

grafana:
  admin:
    passwordKey: admin-password
    userKey: admin-user
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://t-thanos-query:9090
        access: proxy

thanos:
  enabled: true
  existingObjstoreSecret: thanos-storage
  storegateway:
    enabled: true
    sharded:
      enabled: true
    persistence:
      enabled: true
      size: 500Gi
    args:
      - store
      - --log.level=info
      - --log.format=logfmt
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:10902
      - --data-dir=/data
      - --objstore.config-file=/conf/thanos_storage.yaml

  