# Default values for devops-keycloak-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# simple change

replicaCount: 2

image:
  registry: harbor.devops.indico.io/indico-devops
  name: devops-keycloak-service
  pullPolicy: IfNotPresent
  tag: "c14fff22" 

imagePullSecrets:
  - name: harbor-pull-secret
nameOverride: ""
fullnameOverride: "devops-keycloak-service"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: keycloak-service.devops.indico.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: devops-keycloak-service-tls
      hosts:
        - keycloak-service.devops.indico.io

nodeSelector: {}

tolerations: []

affinity: {}

vaultSecrets:
  - name: devops-keycloak-service
    path: tools/argo/data/devops-keycloak-service
    secrets:
      KEYCLOAK_URL: <KEYCLOAK_URL>
      KEYCLOAK_ADMIN_USER: <KEYCLOAK_ADMIN_USER>
      KEYCLOAK_ADMIN_PASSWORD: <KEYCLOAK_ADMIN_PASSWORD>
      KEYCLOAK_CLIENT_ID: <KEYCLOAK_CLIENT_ID>
      KEYCLOAK_CLIENT_SECRET: <KEYCLOAK_CLIENT_SECRET>
