apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    dashboards: external-grafana
  name: external-grafana
  namespace: default
spec:
  external:
    adminPassword:
      key: admin-password
      name: t-grafana
    adminUser:
      key: admin-user
      name: t-grafana
    url: https://thanos-grafana.devops.indico.io
    